In [1]:
import pandas as pd

In [2]:
products = pd.read_excel("data1.xlsx", sheet_name=1)
dynamics = pd.read_excel("data1.xlsx", sheet_name=0)

Сколько уникальных Брендов представлено в нашем магазине?

In [3]:
products['Бренд'].nunique()

1000

У какого бренда больше всего уникальных SKU?

In [4]:
products.groupby('Бренд', as_index=False).agg(n_SKU=('SKU', 'nunique')).sort_values(by='n_SKU', ascending=False).head(1)

         Бренд  n_SKU
443  LUXVISAGE   1541

За какой период времени у нас есть данные о выручке и продажах по SKU?

In [5]:
print(dynamics.sort_values(by='Месяц', ascending=True).head(1)['Месяц'])
print(dynamics.sort_values(by='Месяц', ascending=False).head(1)['Месяц'])

2999   2023-07-01
Name: Месяц, dtype: datetime64[ns]
0   2023-12-01
Name: Месяц, dtype: datetime64[ns]

In [6]:
products

,SKU,Категория,Предмет,Бренд,Цена (Декабрь),Цена (Ноябрь),Продажи (Декабрь),Продажи (Ноябрь),Выручка (Декабрь),Выручка (Ноябрь),Средний % выкупа (Декабрь),Средний % выкупа (Ноябрь),Страна
0,13856867,Уход за кожей,Скрабы,The Act express recovery,413,388.51,109619,110053,45262341,42756691.03,0.96,0.93,Россия
1,46825817,Уход за кожей,Кремы,EpilProfi,839,839.09,48308,48946,40531273,41070099.14,0.96,0.94,Россия
2,51524888,Профессиональная косметика,Гели для бровей,PUSY,850,856.63,40756,39432,34642600,33778634.16,0.96,0.99,Россия
3,56236410,Средства личной гигиены,Влажные салфетки,FRESHLAND,543,555.59,50150,44773,27223489,24875431.07,0.99,1.00,Россия
4,16898570,Макияж,Туши,LUXVISAGE,314,299.82,64598,71601,20294736,21467411.82,0.97,0.94,Беларусь
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91327,116743477,Ногти,Шаблоны для моделирования ногтей,iNVENT P,53,50.97,1,1,53,50.97,0.95,0.95,Россия
91328,104040577,Ногти,Декор для маникюра,iNVENT PRiNT,53,53.24,1,1,53,53.24,0.93,0.93,Россия
91329,43227412,Ногти,Шаблоны для моделирования ногтей,iNVENT P,53,49.55,1,1,53,49.55,0.95,0.95,Россия
91330,104042101,Ногти,Шаблоны для моделирования ногтей,iNVENT P,53,54.93,1,1,53,54.93,0.95,0.95,Россия
91331,42387699,Ногти,Шаблоны для моделирования ногтей,Anna Tkacheva,51,48.72,1,1,51,48.72,0.95,0.95,Россия

> Вариант 2 — “Анализ удовлетворенности покупателей”

Сколько уникальных товарных позиций (SKU) есть в вашем датасете?

In [7]:
products2 = pd.read_excel("data2.xlsx", sheet_name=1)
dynamics2 = pd.read_excel("data2.xlsx", sheet_name=0)

In [8]:
products2['SKU'].nunique()

91332

Сколько различных категорий товаров у бренда AVON?

In [9]:
products.groupby('Бренд', as_index=False).agg(n_SKU=('Категория', 'nunique')).query('Бренд == "AVON"')

   Бренд  n_SKU
25  AVON     11

In [10]:
products.query('Страна == "Республика Корея"')['Бренд'].nunique()

143

Для анализа финансовых показателей у нас есть две таблицы: Dynamic и Product. Чтобы построить аналитику, нужно будет объединить данные. Какой столбец используем для JOIN?

In [12]:
df = products.merge(dynamics, on='Бренд', how='inner')

In [13]:
df

,SKU,Категория,Предмет,Бренд,Цена (Декабрь),Цена (Ноябрь),Продажи (Декабрь),Продажи (Ноябрь),Выручка (Декабрь),Выручка (Ноябрь),Средний % выкупа (Декабрь),Средний % выкупа (Ноябрь),Страна,Месяц,Продажи,Выручка,Средний % выкупа
0,13856867,Уход за кожей,Скрабы,The Act express recovery,413,388.51,109619,110053,45262341,42756691.03,0.96,0.93,Россия,2023-12-01,278198,1.219251e+08,0.961
1,13856867,Уход за кожей,Скрабы,The Act express recovery,413,388.51,109619,110053,45262341,42756691.03,0.96,0.93,Россия,2023-11-01,278829,1.194078e+08,0.966
2,13856867,Уход за кожей,Скрабы,The Act express recovery,413,388.51,109619,110053,45262341,42756691.03,0.96,0.93,Россия,2023-10-01,226272,9.916763e+07,0.870
3,13856867,Уход за кожей,Скрабы,The Act express recovery,413,388.51,109619,110053,45262341,42756691.03,0.96,0.93,Россия,2023-09-01,214046,9.380938e+07,0.910
4,13856867,Уход за кожей,Скрабы,The Act express recovery,413,388.51,109619,110053,45262341,42756691.03,0.96,0.93,Россия,2023-08-01,189028,8.284480e+07,0.879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547987,42387699,Ногти,Шаблоны для моделирования ногтей,Anna Tkacheva,51,48.72,1,1,51,48.72,0.95,0.95,Россия,2023-11-01,6594,8.027356e+05,0.950
547988,42387699,Ногти,Шаблоны для моделирования ногтей,Anna Tkacheva,51,48.72,1,1,51,48.72,0.95,0.95,Россия,2023-10-01,5309,6.640880e+05,0.879
547989,42387699,Ногти,Шаблоны для моделирования ногтей,Anna Tkacheva,51,48.72,1,1,51,48.72,0.95,0.95,Россия,2023-09-01,5094,6.371940e+05,0.892
547990,42387699,Ногти,Шаблоны для моделирования ногтей,Anna Tkacheva,51,48.72,1,1,51,48.72,0.95,0.95,Россия,2023-08-01,5162,6.457000e+05,0.880
547991,42387699,Ногти,Шаблоны для моделирования ногтей,Anna Tkacheva,51,48.72,1,1,51,48.72,0.95,0.95,Россия,2023-07-01,4884,6.109260e+05,0.832

In [14]:
df2 = products2.merge(dynamics2, on='Бренд', how='inner')

In [15]:
df.to_csv('case1.csv')

In [16]:
df2.to_csv('case2.csv')